# Use an official Python runtime as a base image
FROM python:2.7-slim

WORKDIR /basename
COPY nginx.conf requirements.txt /basename/
COPY mriya/requirements.txt /basename/mriya-requirements.txt

RUN pip install -r mriya-requirements.txt
RUN pip install -r requirements.txt

RUN apt-get update -qq && apt-get install -y nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Make port available to the world outside this container
EXPOSE 80

CMD ["/etc/init.d/nginx restart"]
